Use g_return_val_if_fail() in functions expecting a return value
Clang detects that we are not returning any value when function
expects it.

Fixes

| ../../git/panel-plugin/closebutton.c:170:3: error: non-void function 'closebutton_plugin_set_icon' should return a value [-Wreturn-type]
|   g_return_if_fail (XFCE_IS_PANEL_IMAGE (icon));

Signed-off-by: Khem Raj <raj.khem@gmail.com>